package config

import "github.com/ParkWardRR/relaystation/internal/models"

// BuiltinPresets contains the 8 built-in device presets
var BuiltinPresets = map[string]models.Preset{
	"legacy_ipad": {
		ID:           "legacy_ipad",
		Name:         "Legacy iPad",
		Subtitle:     "iPad 2, iPad Mini 1-3, iPad 3-4 (A5-A7, 2011-2014)",
		Description:  "Optimized for Apple A5, A6, and A7 chips. Supports H.264 Main Profile Level 3.1.",
		Codec:        "h264",
		ProfileName:  "main",
		Level:        "3.1",
		Resolution:   "1280x720",
		Bitrate:      "2000k",
		MaxRate:      "2500k",
		FPS:          30,
		AudioBitrate: "128k",
		AudioSample:  "44100",
		Builtin:      true,
	},
	"modern_tablet": {
		ID:           "modern_tablet",
		Name:         "Modern Tablet",
		Subtitle:     "iPad Air, iPad Pro, iPad Mini 4+ (A8+, 2014+)",
		Description:  "For devices with A8 chip or newer. Supports H.264 High Profile Level 4.1.",
		Codec:        "h264",
		ProfileName:  "high",
		Level:        "4.1",
		Resolution:   "1920x1080",
		Bitrate:      "4000k",
		MaxRate:      "5000k",
		FPS:          30,
		AudioBitrate: "192k",
		AudioSample:  "48000",
		Builtin:      true,
	},
	"apple_tv_3": {
		ID:           "apple_tv_3",
		Name:         "Apple TV 3rd Gen",
		Subtitle:     "Apple TV 3 (A1427/A1469)",
		Description:  "Apple TV 3rd generation uses the A5 chip. Supports H.264 Main Profile Level 4.0.",
		Codec:        "h264",
		ProfileName:  "main",
		Level:        "4.0",
		Resolution:   "1280x720",
		Bitrate:      "2500k",
		MaxRate:      "3000k",
		FPS:          30,
		AudioBitrate: "160k",
		AudioSample:  "48000",
		Builtin:      true,
	},
	"mobile_optimized": {
		ID:           "mobile_optimized",
		Name:         "Mobile Optimized",
		Subtitle:     "Low bandwidth / cellular connections",
		Description:  "Designed for mobile viewing over cellular networks. Lower resolution and bitrate.",
		Codec:        "h264",
		ProfileName:  "main",
		Level:        "3.1",
		Resolution:   "854x480",
		Bitrate:      "1000k",
		MaxRate:      "1500k",
		FPS:          30,
		AudioBitrate: "96k",
		AudioSample:  "44100",
		Builtin:      true,
	},
	"high_quality": {
		ID:           "high_quality",
		Name:         "High Quality",
		Subtitle:     "Modern devices with good bandwidth",
		Description:  "Maximum quality for modern devices on fast networks. Full HD with higher bitrate.",
		Codec:        "h264",
		ProfileName:  "high",
		Level:        "4.2",
		Resolution:   "1920x1080",
		Bitrate:      "6000k",
		MaxRate:      "7500k",
		FPS:          60,
		AudioBitrate: "256k",
		AudioSample:  "48000",
		Builtin:      true,
	},
	"hevc_1080p": {
		ID:           "hevc_1080p",
		Name:         "HEVC 1080p",
		Subtitle:     "H.265 for modern devices",
		Description:  "HEVC/H.265 encoding for modern Apple devices. Better compression than H.264.",
		Codec:        "h265",
		ProfileName:  "main",
		Level:        "4.0",
		Resolution:   "1920x1080",
		Bitrate:      "4000k",
		MaxRate:      "5000k",
		FPS:          30,
		AudioBitrate: "192k",
		AudioSample:  "48000",
		Builtin:      true,
	},
	"hevc_max": {
		ID:           "hevc_max",
		Name:         "HEVC Max Quality",
		Subtitle:     "Apple TV 4K, iPad Pro",
		Description:  "Maximum HEVC quality for Apple TV 4K and iPad Pro devices.",
		Codec:        "h265",
		ProfileName:  "main",
		Level:        "4.1",
		Resolution:   "1920x1080",
		Bitrate:      "8000k",
		MaxRate:      "10000k",
		FPS:          30,
		AudioBitrate: "256k",
		AudioSample:  "48000",
		Builtin:      true,
	},
	"passthrough": {
		ID:           "passthrough",
		Name:         "Passthrough",
		Subtitle:     "No transcoding",
		Description:  "Pass through the source stream without re-encoding. Lowest latency.",
		Codec:        "",
		ProfileName:  "",
		Level:        "",
		Resolution:   "",
		Bitrate:      "",
		MaxRate:      "",
		FPS:          0,
		AudioBitrate: "",
		AudioSample:  "",
		Builtin:      true,
	},
}
